version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Shanghai
    target-branch: main
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Asia/Shanghai
    target-branch: main
    open-pull-requests-limit: 10
